# Generated by Django 2.1.7 on 2019-03-30 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Confirmed'), (2, 'Cancelled'), (3, 'Waiting')], default=3, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Availablity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Doctor')),
            ],
            options={
                'verbose_name_plural': 'availablities',
            },
        ),
        migrations.CreateModel(
            name='MiddlewareNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notified', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.TimeField(verbose_name='Appointment time starts')),
                ('available_to', models.TimeField(verbose_name='Appointment time ends')),
            ],
        ),
        migrations.AddField(
            model_name='availablity',
            name='time_slot',
            field=models.ManyToManyField(related_name='available', through='appointment.AvailableTime', to='appointment.TimeSlot'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='availablity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to='appointment.Availablity'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to='appointment.TimeSlot'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeslot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.TimeSlot'),
        ),
    ]
