# Generated by Django 2.1.7 on 2019-03-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('appointment', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Doctor'),
        ),
        migrations.AddField(
            model_name='availablity',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Doctor'),
        ),
        migrations.AddField(
            model_name='availablity',
            name='time_slot',
            field=models.ManyToManyField(through='appointment.AvailableTime', to='appointment.TimeSlot'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='availablity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Availablity'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.TimeSlot'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Department'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Patient'),
        ),
    ]
