# Generated by Django 2.1.7 on 2019-03-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20190317_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Confirmed'), (2, 'Cancelled'), (3, 'Waiting')], null=True),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='availablity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to='appointment.Availablity'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to='appointment.TimeSlot'),
        ),
    ]
