# Generated by Django 2.1.7 on 2019-03-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20190318_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablity',
            options={'verbose_name_plural': 'availablities'},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot_from',
        ),
    ]
