# Generated by Django 2.1.7 on 2019-03-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20190320_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
