# Generated by Django 2.1.7 on 2019-04-09 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paitent',
            new_name='patient',
        ),
    ]
